apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nrf
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nrf-deployment
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nrf
    spec:  
      containers:
        - name: nrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-nrfd", "-c", "/open5gs/config-map/nrf.yaml"]
          volumeMounts:
            - name: {{ .Release.Name }}-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"   
      volumes:
        - name: {{ .Release.Name }}-nrf-config
          configMap:
            name: {{ .Release.Name }}-nrf-config

