apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udm
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udm-deployment
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:     
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"      
      containers:
        - name: udm
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-udmd", "-c", "/open5gs/config-map/udm.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-udm-config
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"   
      volumes:
        - name: {{ .Release.Name }}-udm-config
          configMap:
            name: {{ .Release.Name }}-udm-config
